### ISSUE TITLE
autostart permissions

### ISSUE THREAD

**Issue by Lifespark-Technologies** [Lifespark-Technologies/Proactive-Resource-Direction-Platform#13]

**Comment by ritvij14** [comment]
Auto start permissions were added through autostarter class. It has the popular brands for now. More brands will be added later as needed.
Some errors occurred but they were due to mismatching types and some missing functions which included isPackageExists and startIntent because I tried doing all the things while checking which brand the app is working on. Also added isAutoStartPermissionAvailable to open auto start permissions only if they are available. I had tried adding a companion object like the one that can be used in kotlin to directly implement all functions but couldn't do that. So for now we do it the regular way, create the object and then access the functions.
